### ISSUE TITLE
macOSLAPS and FileVault authentication

### ISSUE THREAD

**Issue by zucchabar** [joshua-d-miller/macOSLAPS-Legacy#10]
Josh,

This has enormous potential so far. It worked within minutes of testing it in our environment and is fairly straight-forward.

The one thing we were able to test and repeat was the scripts inability to change the filevault password when password changes. Almost all of our mac fleet is encrypted, so a password change on this level would require that the FV portion gets addressed.

Has anyone else been able to replicate this?

Best,
Tony

**Comment by joshua-d-miller** [comment]
Tony,

Are you using a local admin account for FileVault authentication? I've never really tested this because I don't let our local admin account unlock the system. I would be willing to test this for you and see what I can come up with. Sounds like ideally we would need to add a key in the config that identifies the user as a FileVault user so the password for that user to unlock the system via FileVault is changed.

Thanks for your input!

**Comment by zucchabar** [comment]
Josh,

We are using a local admin account for FV authentication, but that account is restricted to tech staff. Because of the nature of our federated units and different techs supporting them, it is the method most of our them are familiar with -- no institutionalized keys, just personal ones that are securely stored.

For what it is worth, when we currently push password changes to remote macs, we found that using the 'expect' command allowed us to change the password on a FV enabled user. It changed the logon password as well as the recorded FV password associated with that account.

**Comment by joshua-d-miller** [comment]
So with the 'expect' command you would have to know the old password. To retrieve the password from AD a user has to be authorized to retrieve that password. We are using the computer account to write the password. Could you explain how you are using the 'expect' command in your environment?

**Comment by zucchabar** [comment]
Sure, here is a snippet of a shell script we use. I'll see if I can find the article I referenced for this, but basically using expect mimics changing the password from the GUI, which seems to place nicely with also changing the FV password.

`shopt -s nocasematch
### For MacOS 10.10.x and above
if [[ $osversion -ge "14" ]];then

{
	if [[ ! $acctexist ]];then
		echo "Creating local admin $user for MacOS 10.10.x and higher..."
		sysadminctl -addUser $user -fullName "$displayname" -UID=$userid -password $localpwd -picture "$userpic" -hint somehint
		echo "Adding $user to administrative groups..."
		dseditgroup -o edit -t user -a $user admin
	else
		echo "Local account $user already exists. Resetting password..."
		dscl . create /Users/$user RealName "$displayname"
		dscl . delete /Users/$user jpegphoto
		dscl . delete /Users/$user Picture
		dscl . create /Users/$user Picture "$userpic"
		dseditgroup -o edit -t user -a $user admin
		expect -c"
		spawn passwd $user
		sleep 1
		expect \"assword:\"
		send $localpwd\r
		expect \"assword:\"
		send $localpwd\r
		expect eof"
		#reset to known password which then pushes to FileVault
		expect -c"
		spawn sudo -u $user passwd
		sleep 1
		expect \"assword:\"
		send $localpwd\r
		expect \"assword:\"
		send $localpwd\r
		expect \"assword:\"
		send $localpwd\r
		expect eof"
	fi
}`

**Comment by joshua-d-miller** [comment]
So after reading through this it seems you are passing the password in plain text to 'expect' which would be a huge security vulnerability. I realize that when we generate the password it is in clear text but that is during the password change and once completed it is wiped from memory. This script requires we know the old random password which the only way to retrieve that would be to use an actual AD user that has access to the password. In AD, usually there is one security group that can read the LAPS passwords. If we use that method you now have an AD user's password stored in the script which could present an issue. I know Google has a tool that you might be able to use with this script that could do what you need. https://github.com/google/macops/tree/master/macdestroyer. You would want to utilize the *fdeadduser* tool within. The problem with this script though is that it is a "hidden" functionality that Apple could remove at any point.

**Comment by briend** [comment]
Actually, we don't need to know the old password.  This was a little surprising to me, but this works fine.  Even if we don't know the old password, macOSLAPS will change it on the backend to a new password.  Then we can just change it again (to the same new password) with sudo in the user context so that it magically updates the filevault key.

> 
>                 # Change the password for the account
>                 local_admin_change.changePassword_toPassword_error_(
>                     None, password, None)
>                 output = subprocess.check_output(['/usr/local/sbin/changepass', local_admin, password])

and changepass is just an expect script:

> 
> #!/usr/bin/expect -f
> set username [lindex $argv 0];
> set password [lindex $argv 1];
> 
> spawn sudo -u "$username" passwd
> expect ":"
> send "$password\r"
> expect ":"
> send "$password\r"
> expect ":"
> send "$password\r"

I don't really see a security issue with passing the password to another script.  One bad thing is that if there is an error it will write the password to the log file.

**Comment by joshua-d-miller** [comment]
Hello @briend!

I realize this is a quite a stagnant issue but this has actually been resolved with the Swift version of macOSLAPS which you can get here: https://github.com/joshua-d-miller/macOSLAPS. If you have further questions or concerns please be sure to let me know.

Thanks!
