### ISSUE TITLE
Fails when not "All Domains"

### ISSUE THREAD

**Issue by rmanly** [joshua-d-miller/macOSLAPS-Legacy#4]
I  think this is related to the "any domain in the forest" setting.

But I am supposed to be downstairs in training and I need to run down there. :P

I'll explore more this weekend if no one else has run into it by then.

**Comment by macmule** [comment]
This might be of help, should return the AD Node:

```
#!/usr/bin/python
import sys
import subprocess

from SystemConfiguration import SCDynamicStoreCreate, \
                                SCDynamicStoreCopyValue, \
                                SCDynamicStoreCopyConsoleUser

# Create net_config
net_config = SCDynamicStoreCreate(None, "net", None, None)

# Get AD info
ad_info = dict(SCDynamicStoreCopyValue(net_config, 'com.apple.opendirectoryd.ActiveDirectory'))

# Get node_name from above
node_name = ad_info['NodeName']

# Get domain DNS name from above
domain_dns = ad_info['DomainNameDns']

# Combine for node_name
ad_node = node_name + '/' + domain_dns

print ad_node
```

If I remember my script correctly...

**Comment by joshua-d-miller** [comment]
Thanks for this. I'm actually working on incorporating this and will have a commit as soon as I can.

**Comment by joshua-d-miller** [comment]
Please test the new code and let me know if this resolves your issue.

**Comment by rmanly** [comment]
looks good!
