### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by clburlison** [joshua-d-miller/macOSLAPS-Legacy#7]
Please add a license file to this repo. Apache or MIT are nice. Easy process shown below.

> You can manually add a license using the browser. For example, when you are on a repository home page, you can click on the + icon. To make the process easier, if you name the newly created file LICENSE.md, the license picker automatically appears.
> 
> https://help.github.com/articles/open-source-licensing/#how-can-i-go-back-through-my-public-repositories-and-give-them-licenses

**Comment by joshua-d-miller** [comment]
Now licensed under the MIT license. 👍
